version: 0.2

phases:
    install:
        runtime-versions:
            java: openjdk8
        commands:
            - echo Starting install phase...
        finally:
            - echo Ending install phase...
    pre_build:
        commands:
            - echo Logging in to Amazon ECR - Region $AWS_DEFAULT_REGION ...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
        commands:
            - echo Build $APPLICATION_NAME started on `date`            
            - echo Building the Docker image...
            - docker build -t $APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME .
            - docker tag $APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME
            - printf '[{"name":"%s","imageUri":"%s"}]' $APPLICATION_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME > taskdefinition.json
artifacts:
    files: taskdefinition.json
